steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.learning-api
      - -t
      - gcr.io/$PROJECT_ID/atlas-learning-api-staging
      - .
images:
  - gcr.io/$PROJECT_ID/atlas-learning-api-staging
